export const FONTS = {
  defaults: {
    fontSize: 16,
    lineHeight: 20,
    fontWeight: '400',
    fontFamily: 'Inter-Regular',
    letterSpacing: -0.01,
  },
  largeTitle: {
    fontSize: 32,
    lineHeight: 40,
    fontWeight: '600',
    fontFamily: 'Inter-SemiBold',
    letterSpacing: -0.01,
  },
  title1: {
    fontSize: 24,
    lineHeight: 32,
    fontWeight: '500',
    fontFamily: 'Inter-Medium',
    letterSpacing: -0.01,
  },
  title2: {
    fontSize: 20,
    lineHeight: 24,
    fontWeight: '500',
    fontFamily: 'Inter-Medium',
    letterSpacing: -0.01,
  },
  title3: {
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '500',
    fontFamily: 'Inter-Medium',
    letterSpacing: -0.01,
  },
  subtitle: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '500',
    fontFamily: 'Inter-Medium',
    letterSpacing: -0.01,
  },
  headline: {
    fontSize: 16,
    lineHeight: 20,
    fontWeight: '400',
    fontFamily: 'Inter-Regular',
    letterSpacing: -0.01,
  },
  body: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '400',
    fontFamily: 'Inter-Regular',
    letterSpacing: -0.01,
  },
  bodyBold: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '800',
    fontFamily: 'Inter-Medium',
    letterSpacing: -0.01,
  },
  callout: {
    fontSize: 14,
    lineHeight: 24,
    fontWeight: '500',
    fontFamily: 'Inter-Medium',
    letterSpacing: -0.02,
  },
  subhead: {
    fontSize: 12,
    lineHeight: 20,
    fontWeight: '600',
    fontFamily: 'Inter-SemiBold',
    letterSpacing: -0.01,
  },
  footnote: {
    fontSize: 13,
    lineHeight: 20,
    fontWeight: '400',
    fontFamily: 'Inter-Regular',
    letterSpacing: -0.01,
  },
  caption1: {
    fontSize: 12,
    lineHeight: 24,
    fontWeight: '500',
    fontFamily: 'Inter-Medium',
  },
  caption2: {
    fontSize: 12,
    lineHeight: 20,
    fontWeight: '500',
    fontFamily: 'Inter-Medium',
  },
} as const;
